# Site settings
title: Xuemei Ye blog
email: xuemei-ye@foxmail.com
description: "Musings of a Computer Scientist."
baseurl: ""
url: ""
blogurl: ""
#twitter_username: karpathy
github_username:  xuemei-ye

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-cayman
