# Site settings
title: Xuemei Ye blog
email: xuemei-ye@foxmail.com
description: "Musings of a Computer Scientist."
baseurl: "/"
url: "http://xuemei-ye.github.io"
blogurl: "http://xuemei-ye.github.io/blog"
#twitter_username: karpathy
github_username:  xuemei-ye

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
